name: 💡 Feature Request
description: You get better idea?
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Northern Bitcoiners get plenty better ideas. Drop them here!
  - type: textarea
    attributes:
      label: What do you want us to add?
      placeholder: e.g. Add Hausa voice prompts for USSD, or support Cash pickup for Sell
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which part is affect?
      options: [USSD, Buy/Sell, Recovery, Admin, Nostr, Other]
      multiple: true
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: You want to help?
      options:
        - label: I write code (Rust)
        - label: I translate Hausa
        - label: I test for Kaduna