name: 🙋 Help / Question
description: You jam something?
title: "[HELP] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        No shame to ask. We are all here to learn.
  - type: textarea
    attributes:
      label: what do you want to know?
      placeholder: How can I run the backend in my laptop?
    validations:
      required: true